### ISSUE TITLE
When will the source code be available, please?

### ISSUE THREAD

**Issue by NaVi-start** [SuhZhang/DiffGlue#1]
When will the source code be available, please?

**Comment by SuhZhang** [comment]
Thanks for your attention to our work. So sorry that haven't released the whole repository publicly on GitHub yet. There are too many disturbing things recently that I have to cope with. Anyway, I will try my best to make the code public in the next few weeks. Alternatively, a detailed code description of the model can be [downloaded](https://openreview.net/attachment?id=DVm3Bk2eHh&name=supplementary_material) from our supplemental submission in openreview, which may be helpful.

**Comment by SuhZhang** [comment]
We have uploaded the DiffGlue repository, if you have any questions, please open an issue or contact me via email (suhzhang001@gmail.com). This issue will be closed.
